package com.yq.springframework.test.Sample.context.refreshorder;

import com.yq.springframework.beans.BeansException;
import com.yq.springframework.beans.factory.config.BeanFactoryPostProcessor;
import com.yq.springframework.beans.factory.config.ConfigurableListableBeanFactory;

public class TestBeanDefRegistryPPGenerated implements BeanFactoryPostProcessor {

    StringBuilder sb;

    public TestBeanDefRegistryPPGenerated(StringBuilder sb) {
        this.sb = sb;
    }

    @Override
    public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException {
        sb.append("3");
        System.out.println("bfPP generated by bdrPP append");
    }
}
